/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DwIndexRouteImport } from './routes/dw/index'
import { Route as DwBooksIndexRouteImport } from './routes/dw/books/index'
import { Route as ApiLyricsIndexRouteImport } from './routes/api/lyrics/index'
import { Route as DwApiTestRouteImport } from './routes/dw/api/test'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DwIndexRoute = DwIndexRouteImport.update({
  id: '/dw/',
  path: '/dw/',
  getParentRoute: () => rootRouteImport,
} as any)
const DwBooksIndexRoute = DwBooksIndexRouteImport.update({
  id: '/dw/books/',
  path: '/dw/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLyricsIndexRoute = ApiLyricsIndexRouteImport.update({
  id: '/api/lyrics/',
  path: '/api/lyrics/',
  getParentRoute: () => rootRouteImport,
} as any)
const DwApiTestRoute = DwApiTestRouteImport.update({
  id: '/dw/api/test',
  path: '/dw/api/test',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dw': typeof DwIndexRoute
  '/dw/api/test': typeof DwApiTestRoute
  '/api/lyrics': typeof ApiLyricsIndexRoute
  '/dw/books': typeof DwBooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dw': typeof DwIndexRoute
  '/dw/api/test': typeof DwApiTestRoute
  '/api/lyrics': typeof ApiLyricsIndexRoute
  '/dw/books': typeof DwBooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dw/': typeof DwIndexRoute
  '/dw/api/test': typeof DwApiTestRoute
  '/api/lyrics/': typeof ApiLyricsIndexRoute
  '/dw/books/': typeof DwBooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dw' | '/dw/api/test' | '/api/lyrics' | '/dw/books'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dw' | '/dw/api/test' | '/api/lyrics' | '/dw/books'
  id: '__root__' | '/' | '/dw/' | '/dw/api/test' | '/api/lyrics/' | '/dw/books/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DwIndexRoute: typeof DwIndexRoute
  DwApiTestRoute: typeof DwApiTestRoute
  ApiLyricsIndexRoute: typeof ApiLyricsIndexRoute
  DwBooksIndexRoute: typeof DwBooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dw/': {
      id: '/dw/'
      path: '/dw'
      fullPath: '/dw'
      preLoaderRoute: typeof DwIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dw/books/': {
      id: '/dw/books/'
      path: '/dw/books'
      fullPath: '/dw/books'
      preLoaderRoute: typeof DwBooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lyrics/': {
      id: '/api/lyrics/'
      path: '/api/lyrics'
      fullPath: '/api/lyrics'
      preLoaderRoute: typeof ApiLyricsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dw/api/test': {
      id: '/dw/api/test'
      path: '/dw/api/test'
      fullPath: '/dw/api/test'
      preLoaderRoute: typeof DwApiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DwIndexRoute: DwIndexRoute,
  DwApiTestRoute: DwApiTestRoute,
  ApiLyricsIndexRoute: ApiLyricsIndexRoute,
  DwBooksIndexRoute: DwBooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
