/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DwIndexRouteImport } from './routes/dw/index'
import { Route as ExploreUmapRouteImport } from './routes/explore/umap'
import { Route as ExploreSamenessRouteImport } from './routes/explore/sameness'
import { Route as ExploreEntropyV5RouteImport } from './routes/explore/entropy-v5'
import { Route as ExploreEntropyV4RouteImport } from './routes/explore/entropy-v4'
import { Route as ExploreEntropyV3RouteImport } from './routes/explore/entropy-v3'
import { Route as ExploreEntropyV2RouteImport } from './routes/explore/entropy-v2'
import { Route as ExploreEntropyRigorousRouteImport } from './routes/explore/entropy-rigorous'
import { Route as ExploreEntropyRouteImport } from './routes/explore/entropy'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as DwBooksIndexRouteImport } from './routes/dw/books/index'
import { Route as ApiLyricsIndexRouteImport } from './routes/api/lyrics/index'
import { Route as DwApiTestRouteImport } from './routes/dw/api/test'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DwIndexRoute = DwIndexRouteImport.update({
  id: '/dw/',
  path: '/dw/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreUmapRoute = ExploreUmapRouteImport.update({
  id: '/explore/umap',
  path: '/explore/umap',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreSamenessRoute = ExploreSamenessRouteImport.update({
  id: '/explore/sameness',
  path: '/explore/sameness',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreEntropyV5Route = ExploreEntropyV5RouteImport.update({
  id: '/explore/entropy-v5',
  path: '/explore/entropy-v5',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreEntropyV4Route = ExploreEntropyV4RouteImport.update({
  id: '/explore/entropy-v4',
  path: '/explore/entropy-v4',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreEntropyV3Route = ExploreEntropyV3RouteImport.update({
  id: '/explore/entropy-v3',
  path: '/explore/entropy-v3',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreEntropyV2Route = ExploreEntropyV2RouteImport.update({
  id: '/explore/entropy-v2',
  path: '/explore/entropy-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreEntropyRigorousRoute = ExploreEntropyRigorousRouteImport.update({
  id: '/explore/entropy-rigorous',
  path: '/explore/entropy-rigorous',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreEntropyRoute = ExploreEntropyRouteImport.update({
  id: '/explore/entropy',
  path: '/explore/entropy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const DwBooksIndexRoute = DwBooksIndexRouteImport.update({
  id: '/dw/books/',
  path: '/dw/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLyricsIndexRoute = ApiLyricsIndexRouteImport.update({
  id: '/api/lyrics/',
  path: '/api/lyrics/',
  getParentRoute: () => rootRouteImport,
} as any)
const DwApiTestRoute = DwApiTestRouteImport.update({
  id: '/dw/api/test',
  path: '/dw/api/test',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/inngest': typeof ApiInngestRoute
  '/explore/entropy': typeof ExploreEntropyRoute
  '/explore/entropy-rigorous': typeof ExploreEntropyRigorousRoute
  '/explore/entropy-v2': typeof ExploreEntropyV2Route
  '/explore/entropy-v3': typeof ExploreEntropyV3Route
  '/explore/entropy-v4': typeof ExploreEntropyV4Route
  '/explore/entropy-v5': typeof ExploreEntropyV5Route
  '/explore/sameness': typeof ExploreSamenessRoute
  '/explore/umap': typeof ExploreUmapRoute
  '/dw': typeof DwIndexRoute
  '/dw/api/test': typeof DwApiTestRoute
  '/api/lyrics': typeof ApiLyricsIndexRoute
  '/dw/books': typeof DwBooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/inngest': typeof ApiInngestRoute
  '/explore/entropy': typeof ExploreEntropyRoute
  '/explore/entropy-rigorous': typeof ExploreEntropyRigorousRoute
  '/explore/entropy-v2': typeof ExploreEntropyV2Route
  '/explore/entropy-v3': typeof ExploreEntropyV3Route
  '/explore/entropy-v4': typeof ExploreEntropyV4Route
  '/explore/entropy-v5': typeof ExploreEntropyV5Route
  '/explore/sameness': typeof ExploreSamenessRoute
  '/explore/umap': typeof ExploreUmapRoute
  '/dw': typeof DwIndexRoute
  '/dw/api/test': typeof DwApiTestRoute
  '/api/lyrics': typeof ApiLyricsIndexRoute
  '/dw/books': typeof DwBooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/inngest': typeof ApiInngestRoute
  '/explore/entropy': typeof ExploreEntropyRoute
  '/explore/entropy-rigorous': typeof ExploreEntropyRigorousRoute
  '/explore/entropy-v2': typeof ExploreEntropyV2Route
  '/explore/entropy-v3': typeof ExploreEntropyV3Route
  '/explore/entropy-v4': typeof ExploreEntropyV4Route
  '/explore/entropy-v5': typeof ExploreEntropyV5Route
  '/explore/sameness': typeof ExploreSamenessRoute
  '/explore/umap': typeof ExploreUmapRoute
  '/dw/': typeof DwIndexRoute
  '/dw/api/test': typeof DwApiTestRoute
  '/api/lyrics/': typeof ApiLyricsIndexRoute
  '/dw/books/': typeof DwBooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/inngest'
    | '/explore/entropy'
    | '/explore/entropy-rigorous'
    | '/explore/entropy-v2'
    | '/explore/entropy-v3'
    | '/explore/entropy-v4'
    | '/explore/entropy-v5'
    | '/explore/sameness'
    | '/explore/umap'
    | '/dw'
    | '/dw/api/test'
    | '/api/lyrics'
    | '/dw/books'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/inngest'
    | '/explore/entropy'
    | '/explore/entropy-rigorous'
    | '/explore/entropy-v2'
    | '/explore/entropy-v3'
    | '/explore/entropy-v4'
    | '/explore/entropy-v5'
    | '/explore/sameness'
    | '/explore/umap'
    | '/dw'
    | '/dw/api/test'
    | '/api/lyrics'
    | '/dw/books'
  id:
    | '__root__'
    | '/'
    | '/api/inngest'
    | '/explore/entropy'
    | '/explore/entropy-rigorous'
    | '/explore/entropy-v2'
    | '/explore/entropy-v3'
    | '/explore/entropy-v4'
    | '/explore/entropy-v5'
    | '/explore/sameness'
    | '/explore/umap'
    | '/dw/'
    | '/dw/api/test'
    | '/api/lyrics/'
    | '/dw/books/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiInngestRoute: typeof ApiInngestRoute
  ExploreEntropyRoute: typeof ExploreEntropyRoute
  ExploreEntropyRigorousRoute: typeof ExploreEntropyRigorousRoute
  ExploreEntropyV2Route: typeof ExploreEntropyV2Route
  ExploreEntropyV3Route: typeof ExploreEntropyV3Route
  ExploreEntropyV4Route: typeof ExploreEntropyV4Route
  ExploreEntropyV5Route: typeof ExploreEntropyV5Route
  ExploreSamenessRoute: typeof ExploreSamenessRoute
  ExploreUmapRoute: typeof ExploreUmapRoute
  DwIndexRoute: typeof DwIndexRoute
  DwApiTestRoute: typeof DwApiTestRoute
  ApiLyricsIndexRoute: typeof ApiLyricsIndexRoute
  DwBooksIndexRoute: typeof DwBooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dw/': {
      id: '/dw/'
      path: '/dw'
      fullPath: '/dw'
      preLoaderRoute: typeof DwIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/umap': {
      id: '/explore/umap'
      path: '/explore/umap'
      fullPath: '/explore/umap'
      preLoaderRoute: typeof ExploreUmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/sameness': {
      id: '/explore/sameness'
      path: '/explore/sameness'
      fullPath: '/explore/sameness'
      preLoaderRoute: typeof ExploreSamenessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/entropy-v5': {
      id: '/explore/entropy-v5'
      path: '/explore/entropy-v5'
      fullPath: '/explore/entropy-v5'
      preLoaderRoute: typeof ExploreEntropyV5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/entropy-v4': {
      id: '/explore/entropy-v4'
      path: '/explore/entropy-v4'
      fullPath: '/explore/entropy-v4'
      preLoaderRoute: typeof ExploreEntropyV4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/entropy-v3': {
      id: '/explore/entropy-v3'
      path: '/explore/entropy-v3'
      fullPath: '/explore/entropy-v3'
      preLoaderRoute: typeof ExploreEntropyV3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/entropy-v2': {
      id: '/explore/entropy-v2'
      path: '/explore/entropy-v2'
      fullPath: '/explore/entropy-v2'
      preLoaderRoute: typeof ExploreEntropyV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/entropy-rigorous': {
      id: '/explore/entropy-rigorous'
      path: '/explore/entropy-rigorous'
      fullPath: '/explore/entropy-rigorous'
      preLoaderRoute: typeof ExploreEntropyRigorousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/entropy': {
      id: '/explore/entropy'
      path: '/explore/entropy'
      fullPath: '/explore/entropy'
      preLoaderRoute: typeof ExploreEntropyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dw/books/': {
      id: '/dw/books/'
      path: '/dw/books'
      fullPath: '/dw/books'
      preLoaderRoute: typeof DwBooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lyrics/': {
      id: '/api/lyrics/'
      path: '/api/lyrics'
      fullPath: '/api/lyrics'
      preLoaderRoute: typeof ApiLyricsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dw/api/test': {
      id: '/dw/api/test'
      path: '/dw/api/test'
      fullPath: '/dw/api/test'
      preLoaderRoute: typeof DwApiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiInngestRoute: ApiInngestRoute,
  ExploreEntropyRoute: ExploreEntropyRoute,
  ExploreEntropyRigorousRoute: ExploreEntropyRigorousRoute,
  ExploreEntropyV2Route: ExploreEntropyV2Route,
  ExploreEntropyV3Route: ExploreEntropyV3Route,
  ExploreEntropyV4Route: ExploreEntropyV4Route,
  ExploreEntropyV5Route: ExploreEntropyV5Route,
  ExploreSamenessRoute: ExploreSamenessRoute,
  ExploreUmapRoute: ExploreUmapRoute,
  DwIndexRoute: DwIndexRoute,
  DwApiTestRoute: DwApiTestRoute,
  ApiLyricsIndexRoute: ApiLyricsIndexRoute,
  DwBooksIndexRoute: DwBooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
